sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install theano
  - pip install https://github.com/SMART-Lab/smartlearner/archive/master.zip
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  - nosetests -v
