sudo: false
cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
before_install:
# Install miniconda to avoid compiling scipy
  - mkdir -p download
  - cd download
  - wget -c http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - cd ..
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then conda create --yes -q -n pyenv mkl python=3.3 numpy=1.9.1 scipy=0.14.0 nose=1.3.4 pyparsing=1.5 pip flake8==2.3 six==1.9.0 pep8==1.6.2 pyflakes==0.8.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then conda create --yes -q -n pyenv mkl python=3.4 numpy=1.9.1 scipy=0.14.0 nose=1.3.4 pyparsing=1.5 pip flake8==2.3 six==1.9.0 pep8==1.6.2 pyflakes==0.8.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then conda create --yes -q -n pyenv mkl python=3.5 numpy=1.9.1 scipy=0.14.0 nose=1.3.4 pyparsing=1.5 pip flake8==2.3 six==1.9.0 pep8==1.6.2 pyflakes==0.8.1; fi
  - source activate pyenv
  - pip install theano
  - pip install https://github.com/SMART-Lab/smartlearner/archive/master.zip
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  - nosetests -v
